### ISSUE TITLE
The app crashes if loading FEN strings with backslashes

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#315]
The app crashes if loading FEN strings containing backslashes.

Example:

```
rnbqkbnr\/pppp1ppp\/8\/4p3\/4P3\/8\/PPPP1PPP\/RNBQKBNR w KQkq e6
```

The next figure describes how to replicate the issue from the end-user's perspective.

![output](https://user-images.githubusercontent.com/4062000/171632818-b1e6b264-3856-44ef-a8a9-7c8dc337ad36.gif)
**Figure 1**. The app crashes if loading a FEN string with backslashes.

The console complains with:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'char')
    at Board.js:125:1
    at Array.forEach (<anonymous>)
    at Board.js:97:1
    at Array.forEach (<anonymous>)
    at board (Board.js:96:1)
    at Board (Board.js:159:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)

The above error occurred in the <Board> component:
    at Board (http://localhost:3000/static/js/bundle.js:1239:20)
    at div
    at http://localhost:3000/static/js/bundle.js:11435:66
    at Grid (http://localhost:3000/static/js/bundle.js:34017:87)
    at div
    at http://localhost:3000/static/js/bundle.js:11435:66
    at Grid (http://localhost:3000/static/js/bundle.js:34017:87)
    at Provider (http://localhost:3000/static/js/bundle.js:144920:20)
    at Chess (http://localhost:3000/static/js/bundle.js:1494:20)

Consider adding an error boundary to your tree to customize error handling behavior.
Visit https://reactjs.org/link/error-boundaries to learn more about error boundaries.

Board.js:125 Uncaught TypeError: Cannot read properties of undefined (reading 'char')
    at Board.js:125:1
    at Array.forEach (<anonymous>)
    at Board.js:97:1
    at Array.forEach (<anonymous>)
    at board (Board.js:96:1)
    at Board (Board.js:159:1)
    at renderWithHooks (react-dom.development.js:14985:1)
    at updateFunctionComponent (react-dom.development.js:17356:1)
    at beginWork (react-dom.development.js:19063:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
```

An informative message should be displayed instead: "Invalid FEN."

Keep it up, and happy learning!

**Comment by nicolaerario** [comment]
Can't reproduce. Maybe already fixed?
@programarivm
