### ISSUE TITLE
Uncaught TypeError: Cannot convert undefined or null to object

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#678]
Click on **Play > Play Computer** and create a game. The following error is arbitrarily thrown when playing the computer.

```
Uncaught TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at placePiece (boardSlice.js:71:27)
    at createReducer.ts:294:20
    at produce (immerClass.ts:94:14)
    at createReducer.ts:293:18
    at Array.reduce (<anonymous>)
    at l (createReducer.ts:260:25)
    at reducer (createSlice.ts:372:14)
    at redux.js:560:29
    at hu (<anonymous>:3:1043)
```

![bug](https://github.com/chesslablab/react-chess/assets/4062000/9c5a9df5-ce68-436b-9795-ada27bb90db7)

![bug_02](https://github.com/chesslablab/react-chess/assets/4062000/a875facd-268a-4ea5-94f3-56a3447e6475)

**Comment by programarivm** [comment]
It seems as if this bug can be replicated more easily on a mobile device than on a desktop. Maybe it has to do with the quality of the Internet connection.
