### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'split')

### ISSUE THREAD

**Issue by programarivm** [chesslablab/react-chess#679]
The following sequence of moves threw the error while playing the computer.

```
1.c4 c5 2.Nc3 Nf6 3.g3 e6 4.Bg2 d5 5.cxd5 exd5 6.d4 cxd4 7.Qxd4 Nc6 8.Qd1 d4 9.Nb5 Qa5+
```

```
react-dom.production.min.js:189 TypeError: Cannot read properties of null (reading 'split')
    at vc (chesslablab-reactblab.esm.js:16137:27)
    at wi (react-dom.production.min.js:167:137)
    at Sc (react-dom.production.min.js:197:258)
    at wA (react-dom.production.min.js:292:88)
    at bs (react-dom.production.min.js:280:389)
    at vs (react-dom.production.min.js:280:320)
    at gs (react-dom.production.min.js:280:180)
    at is (react-dom.production.min.js:271:88)
    at ss (react-dom.production.min.js:273:300)
    at Ta (react-dom.production.min.js:127:105)
```

![Screenshot 2023-11-01 20:22:53](https://github.com/chesslablab/react-chess/assets/4062000/94ea597c-cd8f-49ee-9bd6-4db4b528544a)

![Screenshot 2023-11-01 20:23:56](https://github.com/chesslablab/react-chess/assets/4062000/54463457-b4ba-4362-ac15-a0fd3c28471b)

![Screenshot 2023-11-01 20:25:11](https://github.com/chesslablab/react-chess/assets/4062000/235e726d-0781-42ae-a895-10c575c69e6c)

**Comment by alperatalayn** [comment]
Fellow chess developer here, saw your post about the problem on Twitter. Suggestion: try debugging your grabpiece function: 
<img width="437" alt="image" src="https://github.com/chesslablab/react-chess/assets/48330218/fcaeb86c-733b-4fd9-8137-64775aee373b">
 
at some point the `state.fen[state.fen.length - 1]` is null.

Have a great day!
